config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only:[:index,:show,:edit,:update] do
    member do
      get :like_skills
    end
  end
  
  resources :skills, only: [:show, :create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
  end
  
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  post '/like/:skill_id' => 'likes#like', as:'like'
  delete '/unlike/:skill_id' => 'likes#unlike', as:'unlike'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :skill
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  
  validates :title, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
         
  has_many :skills
  has_many :likes
  has_many :like_skills, through: :likes, source: :skill
  
  
  validates :name, presence: true
  # validates :email, presence: true, uniqueness: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  after_filter :clear_flash
  
  include ApplicationHelper
  
  
  private
  def clear_flash
    flash[:notice]=nil
    flash[:alert]=nil
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end 
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      @skill = Skill.new
      @skills = Skill.all.order(created_at: :desc)
    else
      @message = "ようこそWantedSkillsへ！"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like
    @skill = Skill.find(params[:skill_id])
    like = current_user.likes.build(skill_id: @skill.id)
    like.save
  end
  
  def unlike
    @skill = Skill.find(params[:skill_id])
    like = current_user.likes.find_by(skill_id: @skill.id)
    like.destroy
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_skill, only: [:show,:edit,:update,:destroy,:liking_users]
  
  
  def index
    @skills = Skill.all
  end

  def show
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    #@user = User.find(params[:id])
    #@skill.user_id = @user.id
    if @skill.save
      redirect_to @skill, notice:'スキルが保存されました'
    else
      @skills = Skill.all.order(created_at: :desc)
      render 'home/top'
    end
  end

  def edit
  end

  def update
    if @skill.update(skill_params)
      redirect_to @skill, notice: "スキルが更新されました"
    else
      render :edit
    end
  end

  def destroy
    @skill.destroy
    redirect_to root_path
  end
  
  def liking_users
    @users = @skill.liking_users
  end
  
  private
    def set_skill
      @skill = Skill.find(params[:id])
    end
    
    def skill_params
      params.require(:skill).permit(:title,:user_id)
      #最後に:user_id
    end
    
    def correct_user
      skill = Skill.find(params[:id])
      if !current_user?(skill)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :like_skills]


  def index
    @users = User.all
  end


  def show
    @skills = @user.skills
    @title = "スキル一覧"
  end


  # def new
  #   @user = User.new
  # end


  def edit
  end

  # POST /users
  # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   file = params[:user][:image]
    
  #   @user.set_image(file)
    
  #   if @user.save
  #     redirect_to @user, notice: 'ユーザーが保存されました'
  #   else
  #     render :new
  #   end
  # end



  def update
    file = params[:user][:image]

    @user.set_image(file)

    
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end
  
  def like_skills
    @skills = @user.like_skills
    @title = "いいね！一覧"
    
    # showアクションをrenderしてください
    render :show
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @skill = Skill.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
    
    def correct_user
      user = User.find(params[:id])
      if current_user.id != user.id
        redirect_to root_path, alert: "prohibited pages"
      end
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_user?(user)
    current_user.id == user.id
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def image_for(user)
    if user.image
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else

      image_tag "1.png", class: "profile_img"
    end
  end
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WantedSkills</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container">
      
      <div id="logo"><%= link_to "WantedSkills", root_path, class: "title-logo" %></div>
      <% if user_signed_in? %>
        <ul class="header-right">
          <li><%= link_to "ユーザー一覧", users_path %></li>

          <li><%= link_to current_user.email, current_user %></li>
          
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          
        </ul>
      <% else %>
        <ul class="header-right">
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        </ul>
      <% end %>
      
    </div>
  </header>
  
  <div class="container">
    
    <p class="alert alert-success">
      <%= notice %>
    </p>
    
    <!--<p class="alert alert-danger"> なぜか消えないのでコメントアウト-->
    <!--  <%= alert %>-->
    <!--</p>-->
    
    <%= yield %>
    
  </div>

  <div class="container">
    <footer class="footer">
      <div class="small">
        &copy; 2017 @tsukukobaan.
      </div>
    </footer>
  </div>
</body>
</html>

app/views/likes/_like_links.html.erb
<% if current_user.likes.find_by(skill_id: skill.id) %>
  <%= link_to 'いいね！を取り消す', unlike_path(skill.id), method: :delete, remote: true %>
<% else %>
  <%= link_to 'いいね！', like_path(skill.id), method: :post, remote: true %>
<% end %>

app/views/likes/like.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links",skill: @skill  )) %>');
$('#like-count').html('<%= @skill.likes.count %>');

app/views/likes/unlike.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links",skill: @skill  )) %>');
$('#like-count').html('<%= @skill.likes.count %>');

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @skill.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @skill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  ユーザーID
  <%= f.collection_select :user_id, User.all, :id, :id, {prompt: true}, {class: "form-control user-id-field"} %>

  スキルを追加する
  <%= f.text_field :title, { class: "form-control title-field" } %>
  <%= f.submit "保存", { class: "btn primary-btn" } %>
<% end %>

app/views/skills/_skill.html.erb
<li>
    <%= image_for(skill.user) %>
    <span class="user-name">
        <%= skill.user.name %>
    </span>
    <span class="content">
        <%= link_to skill.title, skill_path(skill.id) %>
        <div>
          <small>
            <!--<%= @skill.likes.count %>人がいいね！といっています-->
            <%= link_to skill.likes.count, liking_users_skill_path(skill.id), id: "like-count" %>人が<span id="like-link"><%= render "likes/like_links", skill: skill %></span>といっています
            
          </small>
        </div>
    </span>
</li>

app/views/skills/edit.html.erb
<h1>スキルを編集する</h1>
<%= render 'form' %>

app/views/skills/index.html.erb
<h1>スキルの一覧</h1>
<ul class="skills">
  <%= render @skills %>
</ul>

app/views/skills/liking_users.html.erb
<ul class='show-skill'>
  <%= render @skill %>
</ul>

<h2 class="heading">いいねしているユーザー一覧 </h2>
<ul class='user-list'>
  
  <%= render @users %>
    
</ul>

app/views/skills/new.html.erb
<h1>スキルを追加する</h1>
<%= render 'form' %>

app/views/skills/show.html.erb
<p id="notice" class="alert alert-success">
  <%= notice %>
</p>

<h2>スキル</h2>
<p><%= @skill.title %></p>


<div id="like-link">
  <%= render "likes/like_links", skill: @skill %>
</div>

<div>
  <small>
    <!--<%= @skill.likes.count %>人がいいね！といっています-->
    <%= link_to @skill.likes.count, liking_users_skill_path(@skill.id), id: "like-count" %>人がいいね！といっています
  </small>
</div>

<% if current_user?(@skill.user) %>
  <%= link_to "編集", edit_skill_path(@skill.id), class: "btn edit-btn" %>
  
  <%= link_to "削除", skill_path(@skill.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  名前
  <%= f.text_field :name, class: "form-control name-field" %>

  メールアドレス
  <%= f.text_field :email, class: "form-control email-field" %>
  
  プロフィール画像
  <%= f.file_field :image, class: "form-control image-field" %>

  <%= f.submit '保存', class: "btn primary-btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_for(user) %>
  <%= link_to user.name, user %> |
  <%= user.email %>
</li>

app/views/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザー一覧へ', users_path %>

app/views/users/index.html.erb
<h1 class="heading">ユーザー一覧</h1>
<ul class="user-list">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>新規ユーザー作成</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<aside class="sidebar">
  <section>
    <span class="label">プロフィール画像</span>
    <h3 class="user-info">
      <%= image_for(@user) %>
    </h3>
  </section>
  
  <section>
    <span class="label">ユーザー</span>
    <h3 class="user-info"><%= @user.name %></h3>
  </section>
  
  <section>
    <span class="label">メールアドレス</span>
    <h3 class="user-info"><%= @user.email %></h3>
  </section>
  
  <section>
    <span class="label">ID</span>
    <h3 class="user-info"><%= @user.id %></h3>
  </section>

  <%= link_to @user.likes.count,like_skills_user_path(@user.id) %>つのスキルにいいね!しています
  <!--<%= @user.likes.count %>つのスキルにいいね!しています-->

  <% if current_user?(@user) %>
    <section>
      <small><%= link_to 'プロフィールを編集', edit_user_path(@user) %></small>
    </section>
  <% end %>

</aside>


<ul class="skills">
  <h2><%= @title %></h2>
  <%= render 'skills/form' %>
  <%= render @skills, skill: @skill %>
  <!--, skill: @skill-->
</ul>